### PR TITLE
Israel hdez kiali 683

### PR DESCRIPTION
**Pull request by jshaughn**
@israel-hdez @lucasponce, please take a look at this and see if it is in line with Lucas's change requests.

### CODE REVIEW

**Comment by israel-hdez** [comment]
I'm OK with this. It's covering the two needs.
But now, I'm wondering why we are doing different things between the graph and the service list.

Anyway, we can use this.

**Comment by lucasponce** [comment]
> But now, I'm wondering why we are doing different things between the graph and the service list.

Because in the service list we are implementing validation.
And some valid scenario is "warn if some pod has not a proper version".

For example, it is valid to change the Deployments labels, to not use version=v1 but Version=v1 (at the end is a manual process).

And I think we want to cover that case.

I should also put this comment in the whole discussion, perhaps I could describe better my concerns.

**Comment by israel-hdez** [comment]
Hopefully, we can sync in tomorrow's meeting.
I think understand your concerns, but I have other concerns. In the UI it looks like we are showing the same data in the service list and in the graph. But under the hood, that's not true.

Think about this basic scenario: A k8s service named "reviews" but with a label "app=criticas". Only with this, the "same" service will appear different in the two pages and all links between the graph and the service details pages will be broken.

The way we are resolving for services is _too_ different. We should choose one method and use it consistently.

**Comment by lucasponce** [comment]
Correct.
Prometheus relies on labels that are generated from the default handler (a metric Mixer Rule).
Services list / details use k8s to fetch services and from there, fetch related Istio objects.
The features now are being introduced are the validation of these "mis-configurations".

Some, could be pure corner case, but others can be something normal, as at the end of the day, all configuration (today in Istio 0.7.1) is manual.

I don't think we are going to fix all these cases in a small step, but it will be good to have them identified.

Note, this is going highly change as Istio is planning changes on this area.

**Comment by jshaughn** [comment]
I think the job of Kiali is to help identify issues in the mesh, whether they are configuration or performance.  The graph is focused mainly on performance and is trying to give some hints as to why the perf may be having an issue.  It does this by driving off of metrics to provide topology based on request traffic.  We offer limited info based on config, just enough to maybe help explain traffic issues, like badging services, giving summary info and leading you to a detail view.  I think basically this is an OK approach.  While we do need to keep an eye on consistency I think overall the goal is to use whatever means possible to bring mesh issues to the user's attention.

**Pull request merged**
